[tools]
# language tools
dotnet = "9"
go = "latest"
node = "lts"
rust = "latest"
zig = "0.15"
python = "latest"
uv = "latest"
# dev tools
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
tmux = "latest"
yazi = "latest"
ripgrep = "latest"
fzf = "latest"
jq = "latest"
yq = "latest"
# Docker tools
act = "latest"
lima = "latest"
colima = "latest"
docker-cli = "latest"
docker-compose = "latest"
# AI tools
gemini = "latest"
opencode = "latest"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
# cargo
"cargo:lsd" = "latest"  # ls replacement
"cargo:atuin" = "latest"  # shell history
"cargo:tokei" = "latest"  # line counter
"cargo:jwt-ui" = "latest"  # jwt tui viewer
"cargo:regect" = "latest"  # regex 101 like tui
"cargo:scooter" = "latest"  # folder wide find and replace
"cargo:rustscan" = "latest"  # port scanner
"cargo:starship" = "latest"  # shell prompt
"cargo:bandwhich" = "latest"  # bandwith analyzer
"cargo:hyperfine" = "latest"  # benchmark tool
"cargo:netscanner" = "latest"  # ip scanner
# npm
"npm:poof" = "latest"
"npm:degit" = "latest"
"npm:serve" = "latest"
"npm:neovim" = "latest"
"npm:@antfu/ni" = "latest"
"npm:quicktype" = "latest"
"npm:http-serve" = "latest"
"npm:live-server" = "latest"
"npm:@mcansh/pid-from-port-cli" = "latest"
"npm:@stephansama/find-makefile-targets" = "latest"

[env]
MISE_NODE_COREPACK = true

[settings]
auto_install = true
not_found_auto_install = true
idiomatic_version_file_enable_tools = [
  "elixir",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "yarn",
]

[settings.python]
uv_venv_auto = true
