[tools]
# language tools
dotnet = '9'
go = 'latest'
node = 'lts'
rust = 'latest'
zig = '0.15'

python = 'latest'
uv = 'latest'

# dev tools
lazydocker = 'latest'
lazygit = 'latest'
neovim = 'latest'
tmux = 'latest'
yazi = 'latest'

ripgrep = 'latest'
fzf = 'latest'
jq = 'latest'
yq = 'latest'

act = 'latest'
lima = 'latest'
colima = 'latest'
docker-cli = 'latest'
docker-compose = 'latest'

gemini = 'latest'
opencode = 'latest'

"cargo:lsd" = 'latest'
"cargo:atuin" = 'latest'
"cargo:tokei" = 'latest'
"cargo:jwt-ui" = 'latest'
"cargo:rustscan" = 'latest'
"cargo:starship" = 'latest'
"cargo:bandwhich" = 'latest'
"cargo:hyperfine" = 'latest'
"cargo:netscanner" = 'latest'

"npm:serve" = "latest"
"npm:neovim" = "latest"
"npm:@antfu/ni" = 'latest'
"npm:http-serve" = "latest"
"npm:live-server" = "latest"
"npm:@github/copilot" = "latest"
"npm:@mcansh/pid-from-port-cli" = "latest"
"npm:@stephansama/find-makefile-targets" = "latest"


[env]
MISE_NODE_COREPACK = true


[settings]
auto_install = true
not_found_auto_install = true
idiomatic_version_file_enable_tools = [
  "elixir",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "yarn",
]

[settings.python]
uv_venv_auto = true
